dictionary_of_us_presidents = [
    {"name": "George Washington", "term": "1789–1797", "vice_presidents": ["John Adams"]},
    {"name": "John Adams", "term": "1797–1801", "vice_presidents": ["Thomas Jefferson"]},
    {"name": "Thomas Jefferson", "term": "1801–1809", "vice_presidents": ["Aaron Burr", "George Clinton"]},
    {"name": "James Madison", "term": "1809–1817", "vice_presidents": ["George Clinton", "Elbridge Gerry"]},
    {"name": "James Monroe", "term": "1817–1825", "vice_presidents": ["Daniel D. Tompkins"]},
    {"name": "John Quincy Adams", "term": "1825–1829", "vice_presidents": ["John C. Calhoun"]},
    {"name": "Andrew Jackson", "term": "1829–1837", "vice_presidents": ["John C. Calhoun", "Martin Van Buren"]},
    {"name": "Martin Van Buren", "term": "1837–1841", "vice_presidents": ["Richard Mentor Johnson"]},
    {"name": "William Henry Harrison", "term": "1841", "vice_presidents": ["John Tyler"]},
    {"name": "John Tyler", "term": "1841–1845", "vice_presidents": []},
    {"name": "James K. Polk", "term": "1845–1849", "vice_presidents": ["George M. Dallas"]},
    {"name": "Zachary Taylor", "term": "1849–1850", "vice_presidents": ["Millard Fillmore"]},
    {"name": "Millard Fillmore", "term": "1850–1853", "vice_presidents": []},
    {"name": "Franklin Pierce", "term": "1853–1857", "vice_presidents": ["William R. King"]},
    {"name": "James Buchanan", "term": "1857–1861", "vice_presidents": ["John C. Breckinridge"]},
    {"name": "Abraham Lincoln", "term": "1861–1865", "vice_presidents": ["Hannibal Hamlin", "Andrew Johnson"]},
    {"name": "Andrew Johnson", "term": "1865–1869", "vice_presidents": []},
    {"name": "Ulysses S. Grant", "term": "1869–1877", "vice_presidents": ["Schuyler Colfax", "Henry Wilson"]},
    {"name": "Rutherford B. Hayes", "term": "1877–1881", "vice_presidents": ["William A. Wheeler"]},
    {"name": "James A. Garfield", "term": "1881", "vice_presidents": ["Chester A. Arthur"]},
    {"name": "Chester A. Arthur", "term": "1881–1885", "vice_presidents": []},
    {"name": "Grover Cleveland", "term": "1885–1889", "vice_presidents": ["Thomas A. Hendricks"]},
    {"name": "Benjamin Harrison", "term": "1889–1893", "vice_presidents": ["Levi P. Morton"]},
    {"name": "Grover Cleveland", "term": "1893–1897", "vice_presidents": ["Adlai Stevenson I"]},
    {"name": "William McKinley", "term": "1897–1901", "vice_presidents": ["Garret A. Hobart", "Theodore Roosevelt"]},
    {"name": "Theodore Roosevelt", "term": "1901–1909", "vice_presidents": ["Charles W. Fairbanks"]},
    {"name": "William Howard Taft", "term": "1909–1913", "vice_presidents": ["James S. Sherman"]},
    {"name": "Woodrow Wilson", "term": "1913–1921", "vice_presidents": ["Thomas R. Marshall"]},
    {"name": "Warren G. Harding", "term": "1921–1923", "vice_presidents": ["Calvin Coolidge"]},
    {"name": "Calvin Coolidge", "term": "1923–1929", "vice_presidents": ["Charles G. Dawes"]},
    {"name": "Herbert Hoover", "term": "1929–1933", "vice_presidents": ["Charles Curtis"]},
    {"name": "Franklin D. Roosevelt", "term": "1933–1945", "vice_presidents": ["John Nance Garner", "Henry A. Wallace", "Harry S. Truman"]},
    {"name": "Harry S. Truman", "term": "1945–1953", "vice_presidents": ["Alben W. Barkley"]},
    {"name": "Dwight D. Eisenhower", "term": "1953–1961", "vice_presidents": ["Richard Nixon"]},
    {"name": "John F. Kennedy", "term": "1961–1963", "vice_presidents": ["Lyndon B. Johnson"]},
    {"name": "Lyndon B. Johnson", "term": "1963–1969", "vice_presidents": ["Hubert Humphrey"]},
    {"name": "Richard Nixon", "term": "1969–1974", "vice_presidents": ["Spiro Agnew", "Gerald Ford"]},
    {"name": "Gerald Ford", "term": "1974–1977", "vice_presidents": ["Nelson Rockefeller"]},
    {"name": "Jimmy Carter", "term": "1977–1981", "vice_presidents": ["Walter Mondale"]},
    {"name": "Ronald Reagan", "term": "1981–1989", "vice_presidents": ["George H. W. Bush"]},
    {"name": "George H. W. Bush", "term": "1989–1993", "vice_presidents": ["Dan Quayle"]},
    {"name": "Bill Clinton", "term": "1993–2001", "vice_presidents": ["Al Gore"]},
    {"name": "George W. Bush", "term": "2001–2009", "vice_presidents": ["Dick Cheney"]},
    {"name": "Barack Obama", "term": "2009–2017", "vice_presidents": ["Joe Biden"]},
    {"name": "Donald Trump", "term": "2017–2021", "vice_presidents": ["Mike Pence"]},
    {"name": "Joe Biden", "term": "2021–present", "vice_presidents": ["Kamala Harris"]}
]

